name: 'demo-build-action'
on:
  workflow_dispatch:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yanr'
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: display dist files
        run: ls -la && ls dist/
      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v4
      #   with:
      #     target_branch: gh-pages
      #     build_dir: dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
